### ISSUE TITLE
Doesn't appear to build on OS X

### ISSUE THREAD

**Issue by axman6** [meteogrid/bindings-gdal#6]
For some reason I can't get this to build on OS X, the issue seems to be with `cbits/errorhandler.h`, but I can't see (or find out) why. It doesn't appear to be a problem with finding the gdal libs and headers (I've tried explicitly setting them with `--extra-{include, lib}-dirs=`, both with my gdal install from homebrew and using the version installed with the `install_gdal.sh` script.  [stack-output.txt](https://github.com/albertov/bindings-gdal/files/605158/stack-output.txt) is the output from running `stack build -v`. Happy to help debug this if you have any ideas.

**Comment by ghorn** [comment]
I also get this on debian. First shows up in https://github.com/albertov/bindings-gdal/commit/d5401e989b9162a7cde3a7f7f65d3c8eec681b6e

**Comment by albertov** [comment]
I think it'll be best to revert Setup.hs to 11088aee7ca since all changes since then were to allow building fully static executables and I hardcoded a few things to my environment to achieve it.

I haven't got a debian or osx machine handy to test this. Could you please check if using this version of Setup.hs fixes it so I can revert it?

Thanks

**Comment by ghorn** [comment]
I bet this is related to https://github.com/albertov/bindings-gdal/pull/7

**Comment by albertov** [comment]
Yeah, I also think that it is related to #7. Does b33b49c4a48c1c60da65b98f3df8049b48aa0ad7 fix it?

**Comment by albertov** [comment]
It seems b33b49c does not fix it: https://travis-ci.org/albertov/bindings-gdal/jobs/291994747

**Comment by albertov** [comment]
This was probably caused because `-std=c++11` was being passed to the compiler which clang reports as an error when compiling C sources.

However, after this fix,  `c2hs` complains because it cannot parse some system headers (See https://github.com/visq/language-c/issues/34 and https://github.com/haskell/c2hs/issues/194).

I'm working on fixing this on #10

**Comment by albertov** [comment]
I've just merge a fix which builds correctly on OS X on travis (https://travis-ci.org/albertov/bindings-gdal/builds/292159734).

Note that an unreleased version of `c2hs` is needed to properly parse some system headers (see conversation @ https://github.com/haskell/c2hs/issues/194)
